# Generated by Django 6.0.2 on 2026-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_reset_otp_user_reset_otp_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="doctor_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="doctor_verified",
            field=models.BooleanField(default=True),
        ),
    ]
