# Generated by Django 6.0.2 on 2026-02-20 10:05

from django.db import migrations, models


def backfill_doctor_status(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(role="doctor"):
        if user.doctor_approved and user.doctor_verified:
            user.doctor_status = "approved"
        else:
            user.doctor_status = "pending"
        user.save(update_fields=["doctor_status"])

    User.objects.exclude(role="doctor").update(doctor_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_doctor_approved_user_doctor_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="doctor_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("discarded", "Discarded"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_doctor_status, migrations.RunPython.noop),
    ]
