# Generated by Django 6.0.2 on 2026-02-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_bio_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_owners",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dashboard_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
