# Generated by Django 6.0.2 on 2026-02-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_created_by_doctor_user_dashboard_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_password_reset",
            field=models.BooleanField(default=False),
        ),
    ]
