# Generated by Django 5.2.11 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0007_user_force_password_reset")]

    operations = [
        migrations.AddField(model_name="user", name="admin_login_otp", field=models.CharField(blank=True, max_length=128, null=True)),
        migrations.AddField(model_name="user", name="admin_login_otp_expires_at", field=models.DateTimeField(blank=True, null=True)),
    ]
