apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-backend
  template:
    metadata:
      labels:
        app: pet-backend
    spec:
      containers:
        - name: pet-backend
          image: pet-backend:2.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: DB_HOST
              value: "mysql-service"

            - name: DB_PORT
              value: "3306"


