# Generated by Django 6.0.2 on 2026-02-20 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pet',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='doctorsummary',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorsummary',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='pets.pet'),
        ),
    ]
