# Generated by Django 6.0.2 on 2026-02-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_doctorsummary_created_at_pet_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsummary',
            name='next_vaccination_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsummary',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorsummary',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
