# Generated by Django 6.0.2 on 2026-02-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_doctorsummary_next_vaccination_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
