from django.urls import path
from .views import (
    RegisterView,
    AllUsersView,
    DeleteUser,
    DoctorVerificationView,
    LoginView,
    ForgotPasswordView,
    ResetPasswordView,
    FirstLoginPasswordResetView,
    ToggleUserActiveView,
    CreateAdminView,
    MeView,
    ApprovedDoctorsView,
    UpdateProfileView,
    AdminEmailOtpRequestView,
    AdminEmailOtpVerifyView,
    AdminPasswordResetEmailOtpRequestView,
    AdminPasswordResetEmailOtpConfirmView,
)

urlpatterns = [
    path('register/', RegisterView.as_view()),
    path('all/', AllUsersView.as_view()),
    path('me/', MeView.as_view()),
    path('profile/', UpdateProfileView.as_view()),
    path('approved-doctors/', ApprovedDoctorsView.as_view()),
    path('delete/<int:pk>/', DeleteUser.as_view()),
    path('doctors/<int:pk>/verify/', DoctorVerificationView.as_view()),
    path('users/<int:pk>/active/', ToggleUserActiveView.as_view()),
    path('admins/create/', CreateAdminView.as_view()),
    path('login/', LoginView.as_view()),
    path('admin/email-otp/', AdminEmailOtpRequestView.as_view()),
    path('admin/email-otp/verify/', AdminEmailOtpVerifyView.as_view()),
    path('admin/password-reset/email-otp/', AdminPasswordResetEmailOtpRequestView.as_view()),
    path('admin/password-reset/email-otp/confirm/', AdminPasswordResetEmailOtpConfirmView.as_view()),
    path('forgot-password/', ForgotPasswordView.as_view()),
    path('reset-password/', ResetPasswordView.as_view()),
    path('first-login-reset/', FirstLoginPasswordResetView.as_view()),
]
